export const GET_POKEMONS = "GET_POKEMONS";
export const LOADING = "LOADING";
export const GET_TYPES = "GET_TYPES";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const GET_POKEMON_NAME = "GET_POKEMON_NAME";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_ATTACK = "ORDER_BY_ATTACK";
export const FILTER_TYPES = "FILTER_TYPES";
export const FILTER_CREATED="FILTER_CREATED";
export const FILTER_SPEED ="FILTER_SPEED";

